name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - pair:
              otp: "28"
              elixir: "1.19"
              lint: lint
          - pair:
              otp: "27"
              elixir: "1.19"

          - pair:
              otp: "28"
              elixir: "1.18"
          - pair:
              otp: "27"
              elixir: "1.18"
          - pair:
              otp: "27"
              elixir: "1.17"

          - pair:
              otp: "26"
              elixir: "1.17"
          - pair:
              otp: "26"
              elixir: "1.16"
          - pair:
              otp: "26"
              elixir: "1.15"

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
        if: matrix.pair.elixir == '1.19.x' # Check formatting only with the latest verison
      - run: mix dialyzer
        if: matrix.pair.elixir == '1.19.x' # Run dialyzer only with the latest verison
      - run: mix test