name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          # ex_aws does not support OTP 28.x yet
          # - pair:
          #     otp: 28.x
          #     elixir: 1.18.x             
          - pair:
              otp: 27.x
              elixir: 1.18.x          
          - pair:
              otp: 27.x
              elixir: 1.17.x
          - pair:
              otp: 26.x
              elixir: 1.16.x
          - pair:
              otp: 26.x
              elixir: 1.15.x
          - pair:
              otp: 25.x
              elixir: 1.15.x
          - pair:
              otp: 25.x
              elixir: 1.14.x
          - pair:
              otp: 25.x
              elixir: 1.13.x
          - pair:
              otp: 24.x
              elixir: 1.15.x
          - pair:
              otp: 24.x
              elixir: 1.14.x
          - pair:
              otp: 24.x
              elixir: 1.13.x

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
        if: matrix.pair.elixir == '1.18.x' # Check formatting only with the latest verison
      - run: mix dialyzer
        if: matrix.pair.elixir == '1.18.x' # Run dialyzer only with the latest verison
      - run: mix test