name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - pair:
              otp: 27.x
              elixir: 1.17.x
          - pair:
              otp: 26.x
              elixir: 1.16.x
          - pair:
              otp: 26.x
              elixir: 1.15.x
          - pair:
              otp: 25.x
              elixir: 1.15.x
          - pair:
              otp: 25.x
              elixir: 1.14.x
          - pair:
              otp: 25.x
              elixir: 1.13.x
          - pair:
              otp: 24.x
              elixir: 1.15.x
          - pair:
              otp: 24.x
              elixir: 1.14.x
          - pair:
              otp: 24.x
              elixir: 1.13.x
          - pair:
              otp: 24.x
              elixir: 1.12.x
          - pair:
              otp: 23.x
              elixir: 1.14.x
          - pair:
              otp: 23.x
              elixir: 1.13.x
          - pair:
              otp: 23.x
              elixir: 1.12.x      

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
        if: matrix.elixir == '1.15.x' # Only check formatting with the latest verison
      - run: mix dialyzer
        if: matrix.elixir == '1.15.x'
      - run: mix test